name: rocm-utils
base: core24
version: '7.11.0-20260108-20805388824'
summary: ROCm CLI utilities
description: |
  This snap bundles the ROCm 7.11.x runtime libraries and the
  command‑line tools rocm‑smi, rocminfo, etc.

grade: stable
confinement: strict

layout:
  /opt/rocm:
    symlink: $SNAP/opt/rocm
  /opt/amdgpu:
    symlink: $SNAP/opt/amdgpu

plugs:
  rocm-shm:
    interface: shared-memory
    private: true

apps:
  amd-smi:
    command: opt/rocm/core-7.11/bin/amd-smi
    plugs:
      - hardware-observe
      - system-observe
      - opengl
      - network
      - rocm-shm
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/rocm/core-7.11/lib:$SNAP/opt/amdgpu/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  rocm-smi:
    command: opt/rocm/core-7.11/bin/rocm-smi
    plugs:
      - hardware-observe
      - system-observe
      - opengl
      - network
      - rocm-shm
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/rocm/core-7.11/lib:$SNAP/opt/amdgpu/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  rocminfo:
    command: opt/rocm/core-7.11/bin/rocminfo
    plugs:
      - hardware-observe
      - system-observe
      - process-control
      - opengl
      - network
      - rocm-shm
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/rocm/core-7.11/lib:$SNAP/opt/amdgpu/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

parts:
  apt-repo:
    plugin: nil
    build-packages:
      - wget
      - gpg
      - dpkg-dev
    override-pull: |
      set -e

      mkdir -p /rocm-repo
      cd /rocm-repo
      tar xvf $SNAPCRAFT_PROJECT_DIR/20260108-20805388824.tar.gz
      cd /rocm-repo/20260108-20805388824/pool/main
      dpkg-scanpackages . /dev/null | gzip -9c > Packages.gz

      cat <<EOF > /etc/apt/sources.list.d/rocm.list
      deb [trusted=yes] file:/rocm-repo/20260108-20805388824/pool/main ./
      EOF

      apt update -y

  rocm-debs:
    plugin: nil
    after: [apt-repo]
    stage-packages:
      - libgomp1
      - libatomic1
      - amdrocm-llvm
      - amdrocm-base
      - amdrocm-smi
      - amdrocm-core-gfx1151
      - amdrocm-core7.11-gfx1151
      - amdrocm-runtime7.11
      - amdrocm-runtime
      - amdrocm-gfx1151
      - amdrocm-blas-gfx1151
      - amdrocm-blas7.11-gfx1151
      - amdrocm-ck-gfx1151
      - amdrocm-ck7.11-gfx1151
      - amdrocm-core-gfx1151
      - amdrocm-core-sdk-gfx1151
      - amdrocm-core-sdk7.11-gfx1151
      - amdrocm-core7.11-gfx1151
      - amdrocm-dnn-gfx1151
      - amdrocm-dnn7.11-gfx1151
      - amdrocm-fft-gfx1151
      - amdrocm-fft7.11-gfx1151
      - amdrocm-gfx1151
      - amdrocm-rand-gfx1151
      - amdrocm-rand7.11-gfx1151
      - amdrocm-rccl-gfx1151
      - amdrocm-rccl7.11-gfx1151
      - amdrocm-solver-gfx1151
      - amdrocm-solver7.11-gfx1151
      - amdrocm-sparse-gfx1151
      - amdrocm-sparse7.11-gfx1151
      - amdrocm7.11-gfx1151
    prime:
      - -usr/lib/*/*.a
      - -opt/rocm/lib/*.a
      - -opt/rocm/include
